"""Backfill pass for market candlesticks."""

from __future__ import annotations

from .backfill_config import BackfillConfig
from .backfill_market import (
    BackfillRangeRequest,
    MarketBackfillWindow,
    MarketContext,
    _apply_cursor_window,
    _backfill_market,
    _backfill_state_key,
    _build_backfill_ranges,
    _build_market_backfill_window,
    _dt_to_epoch,
    _fetch_and_insert_candles,
    _fetch_candle_bounds,
    _insert_candle,
    _interval_minutes_for_strike,
    _iter_time_chunks,
    _load_backfill_cursor,
    _market_is_closed,
    _market_time_window,
    _parse_state_epoch,
    _queue_backfill_market,
    _resolve_last_cursor,
    _resolve_market_bounds,
    _store_backfill_cursor,
    _store_cursor_if_needed,
    _update_backfill_cursor,
    backfill_market,
)
from .backfill_scan import (
    BackfillCounts,
    BackfillScanContext,
    EventBackfillContext,
    _backfill_event,
    _backfill_market_with_errors,
    _enqueue_market_backfill,
    _is_connection_error,
    _iter_events,
    _load_min_close_ts,
    _now_s,
    _safe_rollback,
    _scan_backfill_events,
    _should_enqueue_market,
    _upsert_event_or_skip,
    _upsert_market_or_skip,
    backfill_pass,
)
from ..queue.work_queue import QueueConfig, QueuePublisher

__all__ = [
    "BackfillConfig",
    "BackfillRangeRequest",
    "MarketBackfillWindow",
    "MarketContext",
    "EventBackfillContext",
    "BackfillScanContext",
    "BackfillCounts",
    "QueueConfig",
    "QueuePublisher",
    "_safe_rollback",
    "_is_connection_error",
    "_now_s",
    "_market_is_closed",
    "_backfill_state_key",
    "_parse_state_epoch",
    "_load_backfill_cursor",
    "_store_backfill_cursor",
    "_interval_minutes_for_strike",
    "_iter_events",
    "_market_time_window",
    "_dt_to_epoch",
    "_fetch_candle_bounds",
    "_iter_time_chunks",
    "_build_backfill_ranges",
    "_insert_candle",
    "_resolve_last_cursor",
    "_resolve_market_bounds",
    "_apply_cursor_window",
    "_build_market_backfill_window",
    "_store_cursor_if_needed",
    "_fetch_and_insert_candles",
    "_update_backfill_cursor",
    "_backfill_market",
    "backfill_market",
    "_queue_backfill_market",
    "_upsert_event_or_skip",
    "_upsert_market_or_skip",
    "_should_enqueue_market",
    "_enqueue_market_backfill",
    "_backfill_market_with_errors",
    "_backfill_event",
    "_load_min_close_ts",
    "backfill_pass",
    "_scan_backfill_events",
]
